objects/IntegrationSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used for endpoints, timeouts etc</description>
    <fields>
        <fullName>EndPointURL__c</fullName>
        <label>End Point URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HelperClassName__c</fullName>
        <label>Helper Class Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RequestHeader__c</fullName>
        <label>RequestHeader</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>timeOut__c</fullName>
        <label>timeOut</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>IntegrationSettings</label>
</CustomObject>

objects/RequestHeader__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Request Header</label>
</CustomObject>

classes/SampleWeatherHelper_Test.cls
@IsTest(seeAllData = FALSE)
public class SampleWeatherHelper_Test {

    @IsTest
    private static void getCitiesByCountry_test()
    {
        IntegrationSettings__c integrationSetting = new IntegrationSettings__c();
        integrationSetting.Name = 'GlobalWeather';
        integrationSetting.timeOut__c = 30000;
        integrationSetting.EndPointURL__c = 'http://www.webservicex.com/globalweather.asmx';
        integrationSetting.HelperClassName__c = 'SampleWeatherService';
        integrationSetting.RequestHeader__c = 'SOAPBASIC';
        insert integrationSetting;
        Test.setMock(WebServiceMock.class, new SampleWebServiceMockImpl());
        Test.startTest();
        SampleWeatherHelper whObj = new SampleWeatherHelper();
        whObj.getCitiesByCountry('India');
        Test.stopTest();
    }
    
    @IsTest
     private static void getWeather_test()
     {
         SampleWeatherHelper.WeatherWrapper getWeatherWrap=new SampleWeatherHelper.WeatherWrapper();
         getWeatherWrap.CityName='London';
         getWeatherWrap.CountryName='India';
        IntegrationSettings__c integrationSetting = new IntegrationSettings__c();
        integrationSetting.Name = 'GetWeather';
        integrationSetting.timeOut__c = 30000;
        integrationSetting.EndPointURL__c = 'http://www.webservicex.com/globalweather.asmx';
        integrationSetting.HelperClassName__c = 'GetWeatherService';
        integrationSetting.RequestHeader__c = 'SOAPBASIC';
        insert integrationSetting;
        Test.setMock(WebServiceMock.class, new SampleWebServiceMockImplWeather());
        Test.startTest();
        SampleWeatherHelper whObj = new SampleWeatherHelper();
        whObj.getWeather(getWeatherWrap);
        Test.stopTest();
    }
    
}