objects/IntegrationSettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used for endpoints, timeouts etc</description>
    <fields>
        <fullName>Certificate_Name__c</fullName>
        <label>Certificate Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exception_On_OFF__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Webservice Log</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ServiceMethodName__c</fullName>
        <label>Service Method Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>timeOut__c</fullName>
        <label>timeOut</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>IntegrationSettings</label>
</CustomObject>

objects/WebService_Log__c.object
<CustomObject>
    <description>used to store response codes including success and error</description>
    <label>WebService Log</label>
    <nameField>
        <label>WebService Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WebService Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WebserviceLogHelperTest.cls
@isTest
private class WebserviceLogHelperTest {
    
    static testmethod void logStatusTest(){
        
        IntegrationSettings__c iSetting = new IntegrationSettings__c(name='StausLogCallout', timeOut__c = 120000, ServiceMethodName__c = 'GET', Certificate_Name__c = 'testcertificate',
                                                                    Exception_On_OFF__c=true);
        insert iSetting;
        system.assert(iSetting.Id != null);
        
        WebService_Log__c wsLog = new WebService_Log__c(name=iSetting.name);
        insert wsLog;
        system.assert(wsLog.Id != null);
        
        boolean WebserviceRestLogs = true;
        
        test.startTest();
        WebserviceLogHelper.logStatus(wsLog, WebserviceRestLogs);
        test.stopTest();
    }
    
    static testmethod void logStatusByRESTServiceCallTest(){
        
        String jsonString = 'testjson';
        
        IntegrationSettings__c iSetting = new IntegrationSettings__c(name='StausLogCallout', timeOut__c = 120000, ServiceMethodName__c = 'GET', Certificate_Name__c = 'testcertificate',
                                                                    Exception_On_OFF__c=true);
        insert iSetting;
        system.assert(iSetting.Id != null);
        
        test.startTest();
        RESTIntegration restIntg = new RESTIntegration(iSetting.name);
        WebserviceLogHelper.logStatusByRESTServiceCall(jsonString);
        test.stopTest();
    }
    
}