objects/WebService_Log__c.object
<CustomObject>
    <description>used to store response codes including success and error</description>
    <fields>
        <fullName>CalloutStartTime__c</fullName>
        <label>Callout Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Callout_End_Time__c</fullName>
        <label>Callout End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Request_Body__c</fullName>
        <label>Request Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Body__c</fullName>
        <label>Response Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Code__c</fullName>
        <label>Response Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response_Description__c</fullName>
        <description>used to store response descriptions for end user reference</description>
        <label>Response Description</label>
        <type>TextArea</type>
    </fields>
    <label>WebService Log</label>
    <nameField>
        <label>WebService Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WebService Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LogStatusRestCallout.cls
@RestResource(urlMapping='/LogStatusByRestCallout/*')
global class LogStatusRestCallout 
{
   @HttpPost
   global static void createLogs() 
   {
      // Retrieving the request body
      //String body = System.RestContext.request.requestBody.toString().replace('__c','');
      String body = System.RestContext.request.requestBody.toString();
               
      system.debug('b4 deserialized data'+body ); 
      
      //deserializing the request body to wrapper class WebserviceLogWrapper 
      WebserviceLogWrapper objServiceWrapper =(WebserviceLogWrapper)JSON.deserialize(body,WebserviceLogWrapper.class);
      system.debug('$$$$$$$'+objServiceWrapper);
       
      //instantiated to create a Webservice Log       
      WebService_Log__c serviceLog = WebserviceLogHelper.parseServiceLog(objServiceWrapper);
    
      /*serviceLog.Response_Description__c=webStruc.Response_Description;
      serviceLog.Response_Code__c=webStruc.Response_Code;
      serviceLog.Response_Body__c=webStruc.Response_Body;
      serviceLog.Request_Body__c=webStruc.Request_Body;
      serviceLog.CalloutStartTime__c=webStruc.CalloutStartTime;
      serviceLog.Callout_End_Time__c=System.now();
      serviceLog.Name=webStruc.Name;*/
      try
      {
          insert serviceLog; 
          
          List<Attachment> attachList= new List<Attachment>();
          Attachment attach1=new Attachment();
          Attachment attach2=new Attachment();
          if(serviceLog.Response_Body__c !=''&& serviceLog.Response_Body__c !=null)
          {
                Blob b = Blob.valueOf(objServiceWrapper.Response_Body );
                attach1.ParentId = serviceLog.id;
                attach1.Name = 'Response File';
                attach1.Body = b ;
                attachList.add(attach1);
          }
          if(serviceLog.Request_Body__c!=''&& serviceLog.Request_Body__c!=null)
          {
                Blob attach2Body =Blob.valueOf(objServiceWrapper.Request_Body);
                attach2.ParentId = serviceLog.id;
                attach2.Name = 'Request File';
                attach2.Body = attach2Body ;
                system.debug('attachement-->'+attach1);
                attachList.add(attach2);
          }
          try{
                insert attachList;
          }
          catch(Exception e){
                system.debug('Error while creating attachment in REST callout');
          }
          system.debug(serviceLog);
       } 
       catch(Exception e){
            System.debug('Error inserting logs');
       }
                    
                    
   }
}