objects/WebService_Log__c.object
<CustomObject>
    <description>used to store response codes including success and error</description>
    <fields>
        <fullName>Request_Body__c</fullName>
        <label>Request Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Body__c</fullName>
        <label>Response Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>WebService Log</label>
    <nameField>
        <label>WebService Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WebService Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SampleServiceLog.cls
public class SampleServiceLog {

    public void logStatus()
    {
        WebService_Log__c wsLogs = new WebService_Log__c(name='testwslogs', Response_Body__c='test', Request_Body__c='test');
        string requestBody = JSON.serializePretty(wsLogs);
        
        WebserviceLogHelper.logStatusByRESTServiceCall(requestBody);
    }
    
    @AuraEnabled
    public static void logStatusLightning()
    {
        WebserviceLogWrapper wsLogs = new WebserviceLogWrapper();
        wsLogs.name='testwslogs'; 
        wsLogs.Response_Body='test'; 
        wsLogs.Request_Body='test';
        string requestBody = JSON.serializePretty(wsLogs);
        
        WebserviceLogHelper.logStatusByRESTServiceCall(requestBody);
    }
    
}