objects/WebService_Log__c.object
<CustomObject>
    <description>used to store response codes including success and error</description>
    <fields>
        <fullName>CalloutStartTime__c</fullName>
        <label>Callout Start Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>CalloutTime__c</fullName>
        <label>CalloutTime</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Callout_End_Time__c</fullName>
        <label>Callout End Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Request_Body__c</fullName>
        <label>Request Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Body__c</fullName>
        <label>Response Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Code__c</fullName>
        <label>Response Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response_Description__c</fullName>
        <description>used to store response descriptions for end user reference</description>
        <label>Response Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>WebService Log</label>
    <nameField>
        <label>WebService Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WebService Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WebserviceLogHelper.cls
public class WebserviceLogHelper {
  
    public static webservice_Log__c parseServiceLog(WebserviceLogWrapper objServiceWrapper)
    {
        WebService_Log__c serviceLog = new WebService_Log__c();
        serviceLog.Name = objServiceWrapper.Name;
        serviceLog.Callout_End_Time__c = objServiceWrapper.Callout_End_Time;
        serviceLog.CalloutStartTime__c = objServiceWrapper.CalloutStartTime;
        serviceLog.CalloutTime__c = objServiceWrapper.CalloutTime;
        
        if(objServiceWrapper.Request_Body!= null && objServiceWrapper.Request_Body.length() > 32767)  
                objServiceWrapper.Request_Body = objServiceWrapper.Request_Body.substring(0,32767);
        
        if(objServiceWrapper.Response_Body!= null && objServiceWrapper.Response_Body.length() > 32767)  
                objServiceWrapper.Response_Body = objServiceWrapper.Response_Body.substring(0,32767);
        
        serviceLog.Request_Body__c = objServiceWrapper.Request_Body;
        serviceLog.Response_Body__c = objServiceWrapper.Response_Body;
        serviceLog.Response_Code__c = objServiceWrapper.Response_Code;
        serviceLog.Response_Description__c = objServiceWrapper.Response_Description;
        serviceLog.Status__c = objServiceWrapper.status;
        return serviceLog;
    }
    
    public static void logStatus(WebserviceLogWrapper statusLogWrapper, boolean WebserviceRestLogs)
    {        
        WebService_Log__c statusLog = parseServiceLog(statusLogWrapper);
        if(statusLog != null){
            if(WebserviceRestLogs)
            {
                system.debug('WebserviceLogHelper - in if logStatus');
                logStatusByRESTServiceCall(JSON.serializePretty(statusLogWrapper));
                
            }
            else     
            {
                system.debug('WebserviceLogHelper - in else if logStatus');
                insert statusLog;
                
                List<Attachment> attachList= new List<Attachment>();
                Attachment attach1=new Attachment();
                Attachment attach2=new Attachment();
                if(statusLog.Response_Body__c !='' && statusLog.Response_Body__c !=null){
                    Blob b = Blob.valueOf(statusLogWrapper.Response_Body);
                    attach1.ParentId = statusLog.id;
                    attach1.Name = 'Response File';
                    attach1.Body = b ;
                    attachList.add(attach1);
                }
                if(statusLog.Request_Body__c!=''&& statusLog.Request_Body__c!=null){
                    Blob attach2Body =Blob.valueOf(statusLogWrapper.Request_Body);
                    attach2.ParentId = statusLog.id;
                    attach2.Name = 'Request File';
                    attach2.Body = attach2Body ;
                    system.debug('attachement-->'+attach1);
                    attachList.add(attach2);
                }
                try{
                    insert attachList;
                }
                catch(Exception e){
                    system.debug('Error while creating attachment in REST callout');
                }
            }
        }        
    }
    
    public static void logStatusByRESTServiceCall(String jsonString)
    {    
        System.debug('WebserviceLogHelper - logStatusByRESTServiceCall');
        RESTIntegration rest = new RESTIntegration('StausLogCallout');        
        Object status = rest.callout(jsonString);
        system.debug('@@logStatusByRESTServiceCall - status' + status); 
  }
    
}